vich_uploader:
    db_driver: orm

    mappings:
       media_file:
          uri_prefix: /images/publications
          upload_destination: '%kernel.project_dir%/public/images/publications'
          namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
