#index:
#    path: /
#    controller: App\Controller\DefaultController::index

front:
    path: front
    controller: App\Controller\TemplateController::indexFront

app_profile:
    path: /front/profile
    controller: App\Controller\TemplateController::profile



back:
    path: back
    controller: App\Controller\TemplateController::indexBack