#index:
#    path: /
#    controller: App\Controller\DefaultController::index

front:
    path: /front
    controller: App\Controller\TemplateController::indexFront

app_profile:
    path: /front/profile
    controller: App\Controller\TemplateController::profile

back:
    path: /back
    controller: App\Controller\TemplateController::indexBack

home:
    path: /
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\CalendrierController::templateAction'
    defaults:
        template: 'home.html.twig'

about:
    path: /about
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\CalendrierController::templateAction'
    defaults:
        template: 'about.html.twig'

contact:
    path: /contact
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\CalendrierController::templateAction'
    defaults:
        template: 'contact.html.twig'

statistiques:
    path: /statistiques
    controller: 'App\Controller\RendezvousController::statistiques'

app_rendezvous_calendar_by_email:
    path: '/calendar/{emailRepresen}'
    controller: 'App\Controller\RendezvousController::showCalendarByEmail'
    methods: ['GET']

